apiVersion: v1
kind: Service
metadata:
  name: service-go
  namespace: demo
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    name: backend-go
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-node-js
  namespace: demo
data:
  BACKEND_NODE_URL: http://service-node-js.demo.cluster.local:3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-go
  namespace: demo
spec:
  selector:
    matchLabels:
      name: backend-go
  template:
    metadata:
      labels:
        name: backend-go
    spec:
      containers:
        - name: backend
          image: docker.io/nuga99/backend-go
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: configmap-node-js
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 50Mi