services:
  backend-node-js-test:
    image: node:16.20-slim
    working_dir: /app
    entrypoint: bash
    command: -c "npm install && npm test"
    volumes:
      - ./:/app

networks:
  default:
    external:
      name: ci-cd