services:
  backend-node-js:
    build:
      context: ../backend-node-js
      dockerfile: Dockerfile
    container_name: backend-node-js
    ports:
      - "3000:3000"

  backend-go:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: backend-go
    environment:
      - BACKEND_NODE_URL=http://backend-node-js:3000
    ports:
      - "5000:5000"
    depends_on:
      - backend-node-js

networks:
  default:
    external:
      name: ci-cd