apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-node-js
  namespace: dev
spec:
  tls:
  - hosts:
    - node-js.bonestealer.xyz
    secretName: star-bonestealer-xyz-letsencrypt
  rules:
  - host: node-js.bonestealer.xyz
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service-node-js
              port:
                number: 80