name: CD Go

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*go.yml'
      - 'backend-go/**'
  workflow_dispatch:

env:
  KUBERNETES_NAMESPACE: dev
  APPLICATION: backend-go
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test
        run: docker network create ci-cd && make test-${{ env.APPLICATION }}
      
      - name: Build Images
        run: |
          cd ${{ env.APPLICATION }} && \
          docker build --build-arg GIT_SHA=${{ github.sha }} -t ${{ secrets.CONTAINER_REGISTRY }}/${{ env.APPLICATION }} -t ${{ secrets.CONTAINER_REGISTRY }}/${{ env.APPLICATION }}:${{ github.sha }} .

      - name: Push Images
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker push -a ${{ secrets.CONTAINER_REGISTRY }}/${{ env.APPLICATION }}

      - name: Set Kubeconfig
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBECONFIG }}
          kubectl-version: v1.27.4
      
      - name: Deploy Apps
        run: |
          sudo apt-get install gettext-base -y
          export VERSION=${{ github.sha }}
          export CONTAINER_REGISTRY=${{ secrets.CONTAINER_REGISTRY }}
          envsubst < kubernetes/apps/${{ env.APPLICATION }}/deployment.yaml | kubectl apply -f  -
          kubectl apply -f  kubernetes/apps/${{ env.APPLICATION }}/ingress.yaml
        
      - name: Verify Deployment
        run: kubectl rollout status deployment/${{ env.APPLICATION }} -n ${{ env.KUBERNETES_NAMESPACE }}